//
//  Sampledata.swift
//  Yearbook
//
//  Created by Tommy Hailey on 5/26/24.
//

import SwiftUI

public var academyNames = [

    "Adriana Silva",
    "Albert Florido",
    "Alonso del Arte",
    "Ambirr Momon",
    "Amber White",
    "Andrea Cole",
    "Angelo Brown",
    "Ayme Head",
    "Baye Hanne",
    "Brea Pryor",
    "Chantelle Salter",
    "Cleo Larkin",
    "Dana Wakiji",
    "Daijiro Tsushima",
    "Dante Parker",
    "Desmond Blair",
    "Dwayne Toler",
    "Embee Bangoura",
    "Farouk Altahesh",
    "Foster Thompson",
    "Franise Hearn",
    "Henrik Jones",
    "Isabel Sufficool",
    "Jahaira Myers",
    "Jalen Spires",
    "Jalaunda Lewis",
    "Jamal Newton",
    "Jamar Morgan",
    "Jarvis Murray",
    "Javi Torres",
    "Jaysin Myers",
    "Jennifer Daniel",
    "Joe Wolf",
    "John Danial",
    "Kasia Rivers",
    "Kyra Gibbs",
    "Lauren Lindsey",
    "Lawayne Walker",
    "Linda Lewis",
    "Maddi Ashwood",
    "Malik Lyons",
    "Mario Swaidan",
    "Maya Caldwell",
    "Md Asif",
    "Micah Howard",
    "Min Khine",
    "Nicole Lane Huff",
    "Sarah Huguley",
    "Sherrie Cornelius",
    "Stephanie Logan",
    "Syeda Hussain",
    "Takeira Bridges",
    "Tamera Middlebrooks",
    "Tavon Strange",
    "Tommy Hailey",
    "Trionn McKee",
    "Tyson Walker II",
    "Zhané Moorman Taylor",
]
